### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Shaxzy** [MCSulphate/AcceptBot#1]
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'C:\WINDOWS\system32\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:690:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
Press any key to continue . . .

**Comment by develoAll** [comment]
tengo el mismo problema .... espero nos puedan ayudar

**Comment by sulphi-fox** [comment]
Hi! If possible, could you show me how you are running the bot? Thanks!
